---
- name: Run Switch assessment
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
    - output: []
  tasks:  

    - name: "Gather IOS Facts"
      ios_facts:
      register: ios_facts

    - name:  "Run General Cisco Switch Assessment Commands"
      ios_command:
        commands: 
          - show version
          - show run
          - show cdp neighbor
          - show cdp neighbor detail
      register: general_output
      ignore_errors: True

    - name:  "Run Cisco Layer2 Assessment Commands"
      ios_command:
        commands: 
          - show interfaces status
          - show interfaces trunk
          - show interfaces summary
          - show interfaces
          - show int counters errors 
          - show spanning-tree summary 
          - show spanning-tree
          - show etherchannel summary
          - show mac address-table 
          - show vlan
          - show vtp status
      register: l2_output
      ignore_errors: True

    - name:  "Run Cisco Basic Layer3 Assessment Commands"
      ios_command:
        commands: 
          - show ip int brief
          - show ip route
          - show arp
      register: l3_basic_output
      ignore_errors: True

    - name:  "Run Cisco Layer3 Routing Assessment Commands"
      ios_command:
        commands: 
          - show standby brief 
          - show standby
          - show ip cef
          - show ip protocols
          - show ip eigrp neighbor
          - show ip eigrp topology
          - show ip ospf neighbor
          - show ip ospf database
          - show ip bgp summary
          - show ip bgp
      register: l3_routing_output
      ignore_errors: True

    - name:  "Run Cisco Switch Stack Assessment Commands"
      ios_command:
        commands: 
          - show switch
          - show switch detail
          - show switch stack-ring speed
      register: stack_output
      ignore_errors: True
      
    - name:  "Run Cisco Stack Wise Virtual Assessment Commands"
      ios_command:
        commands: 
          - show stackwise-virtual
          - show stackwise-virtual link
          - show stackwise-virtual neighbors
          - show stackwise-virtual dual-active-detection
      register: swv_output
      ignore_errors: True
      

    - name: "debug assessment commands"
      debug:
        msg: "{{ item }}"
      when: "item.failed == 'false' "
      with_items:
        - "{{ general_output }}"
        - "{{ l2_output }}"
        - "{{ l3_basic_output }}"
        - "{{ l3_routing_output }}"
        - "{{ stack_output }}"
        - "{{ swv_output }}"
      tags:
        - debug


    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts
      set_fact:
        device_model: "{{ ios_facts.ansible_facts.ansible_net_model }}"
        ios_version: "{{ ios_facts.ansible_facts.ansible_net_version }}"
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmdd }}"
        state: directory
        mode: 0644
      run_once: yes


    - name: Output to file
      template:
        dest: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-assessment-{{ yyyymmddhhmm }}.txt"
        src: ./templates/assess_switch.j2
        mode: 0644
