---
- name: Build Cisco IOS Facts Inventory
  gather_facts: no
  hosts: all
  tasks:
    - name: Build Local Ansible Facts
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Build Date Time Variables
      set_fact:
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      delegate_to: localhost
      run_once: yes

    - name: Create output directory
      file:
        path: "./output/{{ yyyymmdd }}"
        state: directory
        mode: 0644
      run_once: yes

    - name: Add Hosts to Inventory that fail authentication
      lineinfile:
        line: "{{ item }}"
        path: "./ios-facts-inventory"
        create: yes
        mode: 0644
      with_items:
        - "[reachable]"
        - "[auth-failed]"
        - "[timed-out]"
        - "[denied]"
      run_once: yes
      
    - name: Add hostname to Inventory File 
      block: 
        - name: Gather IOS Facts
          ios_facts:
          register: ios_facts
          
        - name: Debug IOS Facts
          debug:
            msg: "{{ ios_facts | to_nice_json }}"

        - name: Create IOS Facts file
          template:
            src: templates/ios_facts.j2
            dest: "output/{{ yyyymmdd }}/{{ inventory_hostname }}-ios-facts-{{ yyyymmddhhmm }}.txt"
          delegate_to: localhost

        - name: Build IOS Facts Inventory File
          lineinfile:
            line: "{{ ansible_net_hostname }} ansible_host={{ ansible_host }}"
            path: "./ios-facts-inventory"
            create: yes
            mode: 0644
            insertafter: "reachable"

      rescue: 
        - name: Debug Ansible Facts
          debug:
            msg: "{{ ios_facts | to_nice_json }}"

        - name: Add Hosts to Inventory that time out
          lineinfile:
            line: "{{ inventory_hostname }} ansible_host={{ ansible_host }} _error='{{ ios_facts.msg }}'"
            path: "./ios-facts-inventory"
            create: yes
            mode: 0644
            insertafter: "timed-out"
          when: ios_facts.msg is search('Connection timed out') 
          
        - name: Add Hosts to Inventory that fail authentication
          lineinfile:
            line: "{{ inventory_hostname }} ansible_host={{ ansible_host }} _error='{{ ios_facts.msg }}'"
            path: "./ios-facts-inventory"
            create: yes
            mode: 0644
            insertafter: "auth-failed"
          when: ios_facts.msg is search('Authentication failed') 
          
        - name: Add Hosts to Inventory that are denied
          lineinfile:
            line: "{{ inventory_hostname }} ansible_host={{ ansible_host }} _error='{{ ios_facts.msg }}'"
            path: "./ios-facts-inventory"
            create: yes
            mode: 0644
            insertafter: "denied"
          when: ios_facts.msg is search('Unable to connect to port 22') 
