---
- name: Build report of 'inventory_hostname' and 'ansible_host'
  hosts: all
  gather_facts: yes
  serial: 1
  vars:
    - filename: hostname_ip.csv
    - output_directory: ./output
  ignore_errors: True
  tasks:   
    - name: Set Facts
      set_fact:
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      run_once: yes
      
    - name: Write hostname and ip to csv file
      lineinfile:
        line: "{{ inventory_hostname }},{{ ansible_host }}"
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ filename }}"
        create: yes
      delegate_to: localhost

 