---
- name: Find {{ exec_command }} configs in IOS devices
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
  tasks:  
    - name: Gather IOS Facts
      ios_facts:
      register: ios_facts

    - name:  "{{ exec_command }}"
      ios_command:
        commands: 
          - "{{ exec_command }}"
      register: output

    - name: "debug {{ exec_command }}"
      debug:
        msg: "{{ output.stdout_lines }}"
      tags:
        - debug

    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts
      set_fact:
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
        exec_command_scrubbed: "{{ exec_command|replace(' ','-')|replace('|','-')|replace('^','')|replace('$','')|replace('[','')|replace(']','') }}"
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmdd }}"
        state: directory
        mode: 0644
      run_once: yes


    - name: Write Command Output to file
      template:
        src: "./templates/run_exec_command.j2"
        dest: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-{{ exec_command_scrubbed }}-{{ yyyymmddhhmm }}.txt"
      delegate_to: localhost


    - name: Consolidate Command Output to one file
      shell: "/bin/cat {{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-{{ exec_command_scrubbed }}-{{ yyyymmddhhmm }}.txt >> {{ output_directory }}/{{ yyyymmdd }}/{{ exec_command_scrubbed }}-{{ yyyymmddhhmm }}.txt"
      delegate_to: localhost
      tags:
        - consolidate
 
    - name: Delete 
      file:
        path: "{{ output_directory }}/{{ yyyymmdd}}/{{ inventory_hostname }}-{{ exec_command_scrubbed }}-{{ yyyymmddhhmm }}.txt"
        state: absent
        mode: 0644
      delegate_to: localhost
      tags:
        - delete





