---
- name: Write command output  to a file
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
    - ansible_command_timeout: 60
    - ios_cmd: 'show running-config'
  tasks:
    - name: "{{ ios_cmd }}"
      ios_command:
        commands: "{{ ios_cmd }}"
      register: ios_cmd_output

    - name: Debug '{{ ios_cmd }}'
      debug:
        msg: "{{ ios_cmd_output }}"
      tags:
        - debug

    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts (time)
      set_fact:
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}-{{ ios_cmd | replace('\ ','_') }}"
        state: directory
        mode: 0644
      run_once: yes
      
    - name: Write '{{ ios_cmd }}' to file
      copy:
        content: "{{ ios_cmd_output.stdout_lines.0 | join('\n') }}"
        dest: "{{ output_directory }}/{{ yyyymmddhhmm }}-{{ ios_cmd | replace('\ ','_') }}/{{ inventory_hostname }}-{{ ios_cmd | replace('\ ','_') }}.txt"
      delegate_to: localhost


 
