---
- name: Write command output  to a file
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
    - ansible_command_timeout: 60
    - ios_cmd: 'show running-config'
  tasks:
    - name: Gather ios facts
      ios_facts:
      register: ios_facts

    - name: "{{ ios_cmd }}"
      ios_command:
        commands: "{{ ios_cmd }}"
      register: ios_cmd_output

    - name: Debug '{{ ios_cmd }}'
      debug:
        msg: "{{ ios_cmd_output }}"
      tags:
        - debug

    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts (time)
      set_fact:
        device_model: "{{ ios_facts.ansible_facts.ansible_net_model }}"
        ios_version: "{{ ios_facts.ansible_facts.ansible_net_version }}"
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmdd }}"
        state: directory
        mode: 0644
      run_once: yes
      
    - name: Write '{{ ios_cmd }}' to file
      copy:
        content: "{{ ios_cmd_output.stdout_lines.0 | join('\n') }}"
        dest: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-{{ ios_cmd | replace('\ ','_') }}-{{ yyyymmddhhmm }}.txt"
      delegate_to: localhost
    

    - name: Write Header to file
      blockinfile:
        block: |


          !-----------------------------------------------------------
          ! {{ inventory_hostname }} - {{ device_model }} ({{ ios_version }})
          ! Mgmt IP: {{ ansible_host }}
          ! {{ ios_cmd }}
          !-----------------------------------------------------------

        path: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-show-run-{{ search_text_scrubbed}}-{{ yyyymmddhhmm }}.txt"
        marker: ""
        create: yes
        mode: 0644
        insertbefore: BOF 
      delegate_to: localhost


 
