---
- name: Output 'show run section' for {{ search_text }}
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
    - ansible_command_timeout: 60
  tasks:  
    - name: show run | s {{ search_text }}
      ios_command:
        commands: 
          - "show run | s {{ search_text }}"
      register: output

    - name: debug show run | sec {{ search_text }}
      debug:
        msg: "{{ output.stdout_lines }}"
      tags:
        - debug
        
    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts
      set_fact:
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
        search_text_scrubbed: "{{ search_text|replace(' ','_')|replace('|','-')|replace('^','')|replace('$','')|replace('[','')|replace(']','') }}"
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}"
        state: directory
        mode: 0644
      run_once: yes

    - name: Write Output to file
      lineinfile:
        line: "\n\n\n!-- {{ inventory_hostname }}  --!\n"
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}_{{ search_text_scrubbed}}.txt"
        create: yes
        mode: 0644
      delegate_to: localhost

    - name: Write Configs to file
      lineinfile:
        line: "{{ item }}"
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}_{{ search_text_scrubbed }}.txt"
        mode: 0644
      with_items: "{{ output.stdout_lines.0 }}"
      delegate_to: localhost
      tags:
        - consolidate

    - name: Consolidate interface config files to one file
      shell: "/bin/cat {{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}_{{ search_text_scrubbed }}.txt >> {{ output_directory }}/{{ yyyymmddhhmm }}/show-run-{{ search_text_scrubbed }}.txt"
      delegate_to: localhost
      tags:
        - consolidate
 
    - name: Consolidate interface config files to one file
      file:
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}_{{ search_text_scrubbed }}.txt"
        state: absent
        mode: 0644
      delegate_to: localhost
      tags:
        - delete





