---
- name: Configure SNMPv3
  hosts: all
  gather_facts: no
  vars:
    - output_directory: ./output
  tasks:  
    #--------------------------------------------------------
    # Gather ansible facts to set timestamps
    #--------------------------------------------------------

    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts
      set_fact:
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      delegate_to: localhost
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmdd }}"
        state: directory
        mode: 0644
      delegate_to: localhost
      run_once: yes

    #--------------------------------------------------------
    # Get existing SNMP config, print to screen and write to file
    #--------------------------------------------------------

    - name:  "Gather existing snmp configuration"
      ios_command:
        commands: 
          - "show run | include [Ss][Nn][Mm][Pp]"
      register: snmp_config

    - name: "SNMP Config Before"
      debug:
        msg: "{{ snmp_config.stdout_lines }}"
      tags:
        - debug

    - name: Write previous SNMP configuration to file
      copy:
        content: "{{ snmp_config.stdout.0 }}"
        dest: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-snmp_config.txt"
      delegate_to: localhost

    - name: Write Output Header to file
      lineinfile:
        line: "\n\n\n!-- {{ inventory_hostname }} - snmp_config - {{ yyyymmddhhmm }} --!\n"
        path: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-snmp_config.txt"
        create: yes
        # backrefs: yes
        insertbefore: BOF
        mode: 0644
      delegate_to: localhost


    - name: Add Previous SNMP config to a central file
      shell: "/bin/cat {{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-snmp_config.txt >> {{ output_directory }}/{{ yyyymmdd }}/all-snmp_config.txt"
      delegate_to: localhost
      tags:
        - consolidate
 
    #    - name: Delete 
    #      file:
    #        path: "{{ output_directory }}/{{ yyyymmdd }}/{{ inventory_hostname }}-{{ exec_command_scrubbed }}.txt"
    #        state: absent
    #      delegate_to: localhost
    #      tags:
    #        - delete





